/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import dao.AlunoDAO;
import dao.DisciplinaDAO;
import dao.MatriculaDAO;
import helpers.Helpers;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Aluno;
import models.Disciplina;
import models.Matricula;

/**
 *
 * @author Lenovo
 */
public class IfrmNotas extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrmMatricular
     */
    public IfrmNotas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtpesquisaAlunoMatriculado = new javax.swing.JTextField();
        btnpesquisaAlunoMatriculado = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaAlunosMatriculados = new javax.swing.JTable();
        btncadastrarnotas = new javax.swing.JButton();
        txtav1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtav2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtav3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblmedia_final = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Gerenciar Notas");

        txtpesquisaAlunoMatriculado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtpesquisaAlunoMatriculado.addActionListener(this::txtpesquisaAlunoMatriculadoActionPerformed);
        txtpesquisaAlunoMatriculado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpesquisaAlunoMatriculadoKeyPressed(evt);
            }
        });

        btnpesquisaAlunoMatriculado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnpesquisaAlunoMatriculado.setText("Pesquisar");
        btnpesquisaAlunoMatriculado.addActionListener(this::btnpesquisaAlunoMatriculadoActionPerformed);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("Aluno");

        tabelaAlunosMatriculados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Matricula", "Nome", "Disciplina", "Av1", "Av2", "Av3", "Media"
            }
        ));
        tabelaAlunosMatriculados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaAlunosMatriculadosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaAlunosMatriculados);

        btncadastrarnotas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btncadastrarnotas.setText("Cadastrar notas");
        btncadastrarnotas.addActionListener(this::btncadastrarnotasActionPerformed);

        jLabel1.setText("AV1");

        jLabel2.setText("AV2");

        jLabel3.setText("AV3");

        jLabel4.setText("Media");

        lblmedia_final.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel26)
                        .addGap(40, 40, 40)
                        .addComponent(txtpesquisaAlunoMatriculado, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(btnpesquisaAlunoMatriculado))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(lblmedia_final)
                        .addGap(220, 220, 220)
                        .addComponent(btncadastrarnotas))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(29, 29, 29)
                            .addComponent(txtav3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGap(29, 29, 29)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtav1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(txtav2)))))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtpesquisaAlunoMatriculado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpesquisaAlunoMatriculado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtav1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtav2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtav3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncadastrarnotas)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(lblmedia_final)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpesquisaAlunoMatriculadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesquisaAlunoMatriculadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpesquisaAlunoMatriculadoActionPerformed

    private void txtpesquisaAlunoMatriculadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisaAlunoMatriculadoKeyPressed
        //1 - receber o texto
        String nome = "%" + txtpesquisaAlunoMatriculado.getText() + "%";

        //1 - instanciar um objeto da classe MatriculaDAO
        MatriculaDAO dao = new MatriculaDAO();
        List<Matricula> lista = dao.buscarMatriculaPorNomeAluno(nome);

        //2 - Criar o DefaultTableModel (conteúdo da tabela)
        DefaultTableModel conteudo = (DefaultTableModel) tabelaAlunosMatriculados.getModel();
        conteudo.setNumRows(0);

        //3 - Montar o conteúdo para exibir na tabela
        for (Matricula matricula : lista) {
            conteudo.addRow(new Object[]{
                matricula.getId_matricula(),
                matricula.getNomeAluno(),
                matricula.getNomeDisciplina(),
                matricula.getAv1(),
                matricula.getAv2(),
                matricula.getAv3(),
                matricula.getMediaFinal()
            });
        }
    }//GEN-LAST:event_txtpesquisaAlunoMatriculadoKeyPressed

    private void btnpesquisaAlunoMatriculadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesquisaAlunoMatriculadoActionPerformed
        //1 - receber o texto
        String nome = "%" + txtpesquisaAlunoMatriculado.getText() + "%";

        //1 - instanciar um objeto da classe MatriculaDAO
        MatriculaDAO dao = new MatriculaDAO();
        List<Matricula> lista = dao.buscarMatriculaPorNomeAluno(nome);

        //2 - Criar o DefaultTableModel (conteúdo da tabela)
        DefaultTableModel conteudo = (DefaultTableModel) tabelaAlunosMatriculados.getModel();
        conteudo.setNumRows(0);

        //3 - Montar o conteúdo para exibir na tabela
        for (Matricula matricula : lista) {
            conteudo.addRow(new Object[]{
                matricula.getId_matricula(),
                matricula.getNomeAluno(),
                matricula.getNomeDisciplina(),
                matricula.getAv1(),
                matricula.getAv2(),
                matricula.getAv3(),
                matricula.getMediaFinal()
            });
        }
    }//GEN-LAST:event_btnpesquisaAlunoMatriculadoActionPerformed

    private void tabelaAlunosMatriculadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaAlunosMatriculadosMouseClicked
        txtav1.setText(tabelaAlunosMatriculados.getValueAt(tabelaAlunosMatriculados.getSelectedRow(), 3).toString());
        txtav2.setText(tabelaAlunosMatriculados.getValueAt(tabelaAlunosMatriculados.getSelectedRow(), 4).toString());
        txtav3.setText(tabelaAlunosMatriculados.getValueAt(tabelaAlunosMatriculados.getSelectedRow(), 5).toString());
        lblmedia_final.setText(tabelaAlunosMatriculados.getValueAt(tabelaAlunosMatriculados.getSelectedRow(), 6).toString());
    }//GEN-LAST:event_tabelaAlunosMatriculadosMouseClicked

    private void btncadastrarnotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastrarnotasActionPerformed
        try {
            //1 - Receber os dados
            Matricula obj = new Matricula();

            obj.setId_matricula(Integer.parseInt(tabelaAlunosMatriculados.getValueAt(tabelaAlunosMatriculados.getSelectedRow(), 0).toString()));
            
            obj.setAv1(Double.parseDouble(txtav1.getText()));
            obj.setAv2(Double.parseDouble(txtav2.getText()));
            obj.setAv3(Double.parseDouble(txtav3.getText()));
            
            obj.calcularMedia();

            //2 - Criar o objeto DAO pra salvar no banco
            MatriculaDAO dao = new MatriculaDAO();
            dao.alterarNotas(obj);
            
            //Limpar campos de Texto
            txtav1.setText("");
            txtav2.setText("");
            txtav3.setText("");
            lblmedia_final.setText(".");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro " + e);
        }
    }//GEN-LAST:event_btncadastrarnotasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncadastrarnotas;
    private javax.swing.JButton btnpesquisaAlunoMatriculado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblmedia_final;
    private javax.swing.JTable tabelaAlunosMatriculados;
    private javax.swing.JTextField txtav1;
    private javax.swing.JTextField txtav2;
    private javax.swing.JTextField txtav3;
    private javax.swing.JTextField txtpesquisaAlunoMatriculado;
    // End of variables declaration//GEN-END:variables
}
