/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import dao.AlunoDAO;
import dao.DisciplinaDAO;
import dao.MatriculaDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Aluno;
import models.Disciplina;
import models.Matricula;

/**
 *
 * @author Lenovo
 */
public class IfrmMatricular extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrmMatricular
     */
    public IfrmMatricular() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtpesquisaDisciplina = new javax.swing.JTextField();
        btnpesquisaDisciplina = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaDisciplinas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtpesquisaAluno = new javax.swing.JTextField();
        btnpesquisaAluno = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaAlunos = new javax.swing.JTable();
        btnmatricular = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Matricular Aluno");

        txtpesquisaDisciplina.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtpesquisaDisciplina.addActionListener(this::txtpesquisaDisciplinaActionPerformed);
        txtpesquisaDisciplina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpesquisaDisciplinaKeyPressed(evt);
            }
        });

        btnpesquisaDisciplina.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnpesquisaDisciplina.setText("Pesquisar");
        btnpesquisaDisciplina.addActionListener(this::btnpesquisaDisciplinaActionPerformed);

        tabelaDisciplinas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Disciplina", "Nome", "Carga Horaria", "Semestre", "Professor"
            }
        ));
        tabelaDisciplinas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaDisciplinasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaDisciplinas);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Disciplina");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(txtpesquisaDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btnpesquisaDisciplina)
                .addContainerGap(111, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpesquisaDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpesquisaDisciplina)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtpesquisaAluno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtpesquisaAluno.addActionListener(this::txtpesquisaAlunoActionPerformed);
        txtpesquisaAluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpesquisaAlunoKeyPressed(evt);
            }
        });

        btnpesquisaAluno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnpesquisaAluno.setText("Pesquisar");
        btnpesquisaAluno.addActionListener(this::btnpesquisaAlunoActionPerformed);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("Aluno");

        tabelaAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Aluno", "Nome", "Curso"
            }
        ));
        tabelaAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaAlunosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaAlunos);

        btnmatricular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnmatricular.setText("Matricular");
        btnmatricular.addActionListener(this::btnmatricularActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(jLabel26)
                                .addGap(40, 40, 40)
                                .addComponent(txtpesquisaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(btnpesquisaAluno))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(297, 297, 297)
                                .addComponent(btnmatricular)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtpesquisaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpesquisaAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnmatricular)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpesquisaAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesquisaAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpesquisaAlunoActionPerformed

    private void txtpesquisaAlunoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisaAlunoKeyPressed
        //1 - receber o texto
        String nome = "%" + txtpesquisaAluno.getText() + "%";

        //1 - instanciar um objeto da classe AlunoDAO
        AlunoDAO dao = new AlunoDAO();
        List<Aluno> lista = dao.buscarAlunoPeloNome(nome);

        //2 - Criar o DefaultTableModel (conteúdo da tabela)
        DefaultTableModel conteudo = (DefaultTableModel) tabelaAlunos.getModel();
        conteudo.setNumRows(0);

        //3 - Montar o conteúdo para exibir na tabela
        for (Aluno aluno : lista) {
            conteudo.addRow(new Object[]{
                aluno.getId_aluno(),
                aluno.getNome(),
                aluno.getCurso()
            });
        }
    }//GEN-LAST:event_txtpesquisaAlunoKeyPressed

    private void btnpesquisaAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesquisaAlunoActionPerformed
        //1 - receber o texto
        String nome = "%" + txtpesquisaAluno.getText() + "%";

        //1 - instanciar um objeto da classe AlunoDAO
        AlunoDAO dao = new AlunoDAO();
        List<Aluno> lista = dao.buscarAlunoPeloNome(nome);

        //2 - Criar o DefaultTableModel (conteúdo da tabela)
        DefaultTableModel conteudo = (DefaultTableModel) tabelaAlunos.getModel();
        conteudo.setNumRows(0);

        //3 - Montar o conteúdo para exibir na tabela
        for (Aluno aluno : lista) {
            conteudo.addRow(new Object[]{
                aluno.getId_aluno(),
                aluno.getNome(),
                aluno.getCurso()
            });
        }
    }//GEN-LAST:event_btnpesquisaAlunoActionPerformed

    private void tabelaAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaAlunosMouseClicked
//        guias.setSelectedIndex(4);
//
//        //Pegar os dados
//        txtid_aluno.setText(tabelaAlunos.getValueAt(tabelaAlunos.getSelectedRow(), 0).toString());
//        txtnome_aluno.setText(tabelaAlunos.getValueAt(tabelaAlunos.getSelectedRow(), 1).toString());
//        txtemail_aluno.setText(tabelaAlunos.getValueAt(tabelaAlunos.getSelectedRow(), 2).toString());
//        txtcurso_aluno.setText(tabelaAlunos.getValueAt(tabelaAlunos.getSelectedRow(), 3).toString());
//        txtwhatsapp_aluno.setText(tabelaAlunos.getValueAt(tabelaAlunos.getSelectedRow(), 4).toString());
//
//        int idSelecionado = Integer.parseInt(tabelaAlunos.getValueAt(tabelaAlunos.getSelectedRow(), 0).toString());
//
//        for (Aluno listaDeAluno : listaDeAlunos) {
//            if(listaDeAluno.getId_aluno() == idSelecionado){
//                txtcelular_aluno.setText(listaDeAluno.getTelefoneCelular());
//                txtendereco_aluno.setText(listaDeAluno.getEndereco());
//                if (listaDeAluno.getData_nascimento() != null) {
//                    java.time.format.DateTimeFormatter formatoBr = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");
//                    String dataFormatada = listaDeAluno.getData_nascimento().format(formatoBr);
//                    txtdata_nascimento_aluno.setText(dataFormatada);
//                }
//            }
//        }
    }//GEN-LAST:event_tabelaAlunosMouseClicked

    private void txtpesquisaDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesquisaDisciplinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpesquisaDisciplinaActionPerformed

    private void txtpesquisaDisciplinaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisaDisciplinaKeyPressed
        //1 - receber o texto
        String nome = "%" + txtpesquisaDisciplina.getText() + "%";

        //1 - instanciar um objeto da classe ProfessorDAO
        DisciplinaDAO dao = new DisciplinaDAO();
        List<Disciplina> lista = dao.buscarDisciplinaPeloNome(nome);

        //2 - Criar o DefaultTableModel (conteúdo da tabela)
        DefaultTableModel conteudo = (DefaultTableModel) tabelaDisciplinas.getModel();
        conteudo.setNumRows(0);

        //3 - Montar o conteúdo para exibir na tabela
        for (Disciplina disciplina : lista) {
            conteudo.addRow(new Object[]{
                disciplina.getId_disciplina(),
                disciplina.getNome(),
                disciplina.getCarga_horaria(),
                disciplina.getSemestre(),
                disciplina.getNomeProfessor()
            });
        }
    }//GEN-LAST:event_txtpesquisaDisciplinaKeyPressed

    private void btnpesquisaDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesquisaDisciplinaActionPerformed
        //1 - receber o texto
        String nome = "%" + txtpesquisaDisciplina.getText() + "%";

        //1 - instanciar um objeto da classe ProfessorDAO
        DisciplinaDAO dao = new DisciplinaDAO();
        List<Disciplina> lista = dao.buscarDisciplinaPeloNome(nome);

        //2 - Criar o DefaultTableModel (conteúdo da tabela)
        DefaultTableModel conteudo = (DefaultTableModel) tabelaDisciplinas.getModel();
        conteudo.setNumRows(0);

        //3 - Montar o conteúdo para exibir na tabela
        for (Disciplina disciplina : lista) {
            conteudo.addRow(new Object[]{
                disciplina.getId_disciplina(),
                disciplina.getNome(),
                disciplina.getCarga_horaria(),
                disciplina.getSemestre(),
                disciplina.getNomeProfessor()
            });
        }
    }//GEN-LAST:event_btnpesquisaDisciplinaActionPerformed

    private void tabelaDisciplinasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaDisciplinasMouseClicked
//        guias.setSelectedIndex(2);
//
//        //Pegar os dados
//        txtid_disciplina.setText(tabelaDisciplinas.getValueAt(tabelaDisciplinas.getSelectedRow(), 0).toString());
//        txtnome_disciplina.setText(tabelaDisciplinas.getValueAt(tabelaDisciplinas.getSelectedRow(), 1).toString());
//        txtcarga_horaria.setText(tabelaDisciplinas.getValueAt(tabelaDisciplinas.getSelectedRow(), 2).toString());
//        txtsemestre.setText(tabelaDisciplinas.getValueAt(tabelaDisciplinas.getSelectedRow(), 3).toString());
//        // Para selecionar o professor no CB vamos fazer uma busca, pois esse Combobox possui um objeto e não uma String
//        String nomeProfessorNaTabela = tabelaDisciplinas.getValueAt(tabelaDisciplinas.getSelectedRow(), 4).toString();
//
//        // Vamos percorrer item por item do ComboBox até achar o professor com o nome
//        for (int i = 0; i < cbprofessor.getItemCount(); i++) {
//            // Pegamos o objeto Professor que está nessa posição
//            Professor profDoItem = (Professor) cbprofessor.getItemAt(i);
//
//            // Verificamos: O nome desse professor é igual ao nome que estava na tabela?
//            if (profDoItem.getNome().equals(nomeProfessorNaTabela)) {
//                // Se for, selecionamos essa posição e paramos o loop (break)
//                cbprofessor.setSelectedIndex(i);
//                break;
//            }
//        }
    }//GEN-LAST:event_tabelaDisciplinasMouseClicked

    private void btnmatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmatricularActionPerformed
        try {
            //1 - Receber os dados
            Matricula obj = new Matricula();

            obj.setId_aluno(Integer.parseInt(tabelaAlunos.getValueAt(tabelaAlunos.getSelectedRow(), 0).toString()));
            obj.setId_disciplina(Integer.parseInt(tabelaDisciplinas.getValueAt(tabelaDisciplinas.getSelectedRow(), 0).toString()));

            //2 - Criar o objeto DAO pra salvar no banco
            MatriculaDAO dao = new MatriculaDAO();
            dao.cadastrarMatricula(obj);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro " + e);
        }
    }//GEN-LAST:event_btnmatricularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnmatricular;
    private javax.swing.JButton btnpesquisaAluno;
    private javax.swing.JButton btnpesquisaDisciplina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabelaAlunos;
    private javax.swing.JTable tabelaDisciplinas;
    private javax.swing.JTextField txtpesquisaAluno;
    private javax.swing.JTextField txtpesquisaDisciplina;
    // End of variables declaration//GEN-END:variables
}
