/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import dao.AlunoDAO;
import dao.DisciplinaDAO;
import dao.MatriculaDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Aluno;
import models.Disciplina;
import models.Matricula;

/**
 *
 * @author Lenovo
 */
public class IfrmGerenciarMatricula extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrmMatricular
     */
    public IfrmGerenciarMatricula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtpesquisaAlunoMatriculado = new javax.swing.JTextField();
        btnpesquisaAlunoMatriculado = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaAlunosMatriculados = new javax.swing.JTable();
        btnTrancarDisciplina = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Gerenciar Matricula");

        txtpesquisaAlunoMatriculado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtpesquisaAlunoMatriculado.addActionListener(this::txtpesquisaAlunoMatriculadoActionPerformed);
        txtpesquisaAlunoMatriculado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpesquisaAlunoMatriculadoKeyPressed(evt);
            }
        });

        btnpesquisaAlunoMatriculado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnpesquisaAlunoMatriculado.setText("Pesquisar");
        btnpesquisaAlunoMatriculado.addActionListener(this::btnpesquisaAlunoMatriculadoActionPerformed);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("Aluno");

        tabelaAlunosMatriculados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Matricula", "ID Aluno", "Nome", "Disciplina"
            }
        ));
        tabelaAlunosMatriculados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaAlunosMatriculadosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaAlunosMatriculados);

        btnTrancarDisciplina.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTrancarDisciplina.setText("Trancar disciplina");
        btnTrancarDisciplina.addActionListener(this::btnTrancarDisciplinaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel26)
                        .addGap(40, 40, 40)
                        .addComponent(txtpesquisaAlunoMatriculado, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(btnpesquisaAlunoMatriculado)
                        .addGap(0, 117, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(btnTrancarDisciplina)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtpesquisaAlunoMatriculado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpesquisaAlunoMatriculado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTrancarDisciplina)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpesquisaAlunoMatriculadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesquisaAlunoMatriculadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpesquisaAlunoMatriculadoActionPerformed

    private void txtpesquisaAlunoMatriculadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisaAlunoMatriculadoKeyPressed
        //1 - receber o texto
        String nome = "%" + txtpesquisaAlunoMatriculado.getText() + "%";

        //1 - instanciar um objeto da classe MatriculaDAO
        MatriculaDAO dao = new MatriculaDAO();
        List<Matricula> lista = dao.buscarMatriculaPorNomeAluno(nome);

        //2 - Criar o DefaultTableModel (conteúdo da tabela)
        DefaultTableModel conteudo = (DefaultTableModel) tabelaAlunosMatriculados.getModel();
        conteudo.setNumRows(0);

        //3 - Montar o conteúdo para exibir na tabela
        for (Matricula matricula : lista) {
            conteudo.addRow(new Object[]{
                matricula.getId_matricula(),
                matricula.getId_aluno(),
                matricula.getNomeAluno(),
                matricula.getNomeDisciplina()
            });
        }
    }//GEN-LAST:event_txtpesquisaAlunoMatriculadoKeyPressed

    private void btnpesquisaAlunoMatriculadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesquisaAlunoMatriculadoActionPerformed
        //1 - receber o texto
        String nome = "%" + txtpesquisaAlunoMatriculado.getText() + "%";

        //1 - instanciar um objeto da classe MatriculaDAO
        MatriculaDAO dao = new MatriculaDAO();
        List<Matricula> lista = dao.buscarMatriculaPorNomeAluno(nome);

        //2 - Criar o DefaultTableModel (conteúdo da tabela)
        DefaultTableModel conteudo = (DefaultTableModel) tabelaAlunosMatriculados.getModel();
        conteudo.setNumRows(0);

        //3 - Montar o conteúdo para exibir na tabela
        for (Matricula matricula : lista) {
            conteudo.addRow(new Object[]{
                matricula.getId_matricula(),
                matricula.getId_aluno(),
                matricula.getNomeAluno(),
                matricula.getNomeDisciplina()
            });
        }
    }//GEN-LAST:event_btnpesquisaAlunoMatriculadoActionPerformed

    private void tabelaAlunosMatriculadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaAlunosMatriculadosMouseClicked
//        guias.setSelectedIndex(4);
//
//        //Pegar os dados
//        txtid_aluno.setText(tabelaAlunos.getValueAt(tabelaAlunos.getSelectedRow(), 0).toString());
//        txtnome_aluno.setText(tabelaAlunos.getValueAt(tabelaAlunos.getSelectedRow(), 1).toString());
//        txtemail_aluno.setText(tabelaAlunos.getValueAt(tabelaAlunos.getSelectedRow(), 2).toString());
//        txtcurso_aluno.setText(tabelaAlunos.getValueAt(tabelaAlunos.getSelectedRow(), 3).toString());
//        txtwhatsapp_aluno.setText(tabelaAlunos.getValueAt(tabelaAlunos.getSelectedRow(), 4).toString());
//
//        int idSelecionado = Integer.parseInt(tabelaAlunos.getValueAt(tabelaAlunos.getSelectedRow(), 0).toString());
//
//        for (Aluno listaDeAluno : listaDeAlunos) {
//            if(listaDeAluno.getId_aluno() == idSelecionado){
//                txtcelular_aluno.setText(listaDeAluno.getTelefoneCelular());
//                txtendereco_aluno.setText(listaDeAluno.getEndereco());
//                if (listaDeAluno.getData_nascimento() != null) {
//                    java.time.format.DateTimeFormatter formatoBr = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");
//                    String dataFormatada = listaDeAluno.getData_nascimento().format(formatoBr);
//                    txtdata_nascimento_aluno.setText(dataFormatada);
//                }
//            }
//        }
    }//GEN-LAST:event_tabelaAlunosMatriculadosMouseClicked

    private void btnTrancarDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrancarDisciplinaActionPerformed
        //Excluir
        try {
            int id = Integer.parseInt(tabelaAlunosMatriculados.getValueAt(tabelaAlunosMatriculados.getSelectedRow(), 0).toString());

            MatriculaDAO dao = new MatriculaDAO();
            dao.excluirMatricula(id);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Selecione um professor");
        }
    }//GEN-LAST:event_btnTrancarDisciplinaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTrancarDisciplina;
    private javax.swing.JButton btnpesquisaAlunoMatriculado;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabelaAlunosMatriculados;
    private javax.swing.JTextField txtpesquisaAlunoMatriculado;
    // End of variables declaration//GEN-END:variables
}
